### ISSUE TITLE
Refresh numberpicker

### ISSUE THREAD

**Issue by TEJ227** [ShawnLin013/NumberPicker#112]
Is there a way possible to change number picker values to set min/max values with displaynames again? 
I am trying to set it again but it crashes. 

`FATAL EXCEPTION: main
    Process: com.bkl.moonguide, PID: 20574
    java.lang.ArrayIndexOutOfBoundsException: length=3; index=11
        at com.shawnlin.numberpicker.NumberPicker.ensureCachedScrollSelectorValue(NumberPicker.java:1890)
        at com.shawnlin.numberpicker.NumberPicker.initializeSelectorWheelIndices(NumberPicker.java:1686)
        at com.shawnlin.numberpicker.NumberPicker.setMaxValue(NumberPicker.java:1424)
        at com.bkl.moonguide.huntscreens.ActJumpToMonth$4.onValueChange(ActJumpToMonth.java:293)
        at com.shawnlin.numberpicker.NumberPicker.notifyChange(NumberPicker.java:1932)
        at com.shawnlin.numberpicker.NumberPicker.setValueInternal(NumberPicker.java:1711)
        at com.shawnlin.numberpicker.NumberPicker.scrollBy(NumberPicker.java:1147)
        at com.shawnlin.numberpicker.NumberPicker.onTouchEvent(NumberPicker.java:913)
        at android.view.View.dispatchTouchEvent(View.java:11776)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
        at com.shawnlin.numberpicker.NumberPicker.dispatchTouchEvent(NumberPicker.java:986)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)`

**Comment by kay14** [comment]
Hi. I had the same issue. I have the number picker inside the RecyclerView and it was not getting refreshed and crashing with a similar error report.
Just to clarify - Are you using the **setDisplayedValues()** method to display custom values in the numberPicker?
If yes, then this solution will resolve your issue.

before calling the **setMinValue()** & **setMaxValue()** method, call this: **setDisplayedValues(null)**. So the flow should be somewhat like this:

**mNumberPicker.setDisplayedValues(null);**
**mNumberPicker.setMinValue(1);**
**mNumberPicker.setMaxValue(mDisplayValues.length);**
**mNumberPicker.setDisplayedValues(mDisplayValues);**

Hope this helps. Good luck!

**Comment by dandaev** [comment]
> Hi. I had the same issue. I have the number picker inside the RecyclerView and it was not getting refreshed and crashing with a similar error report.
> Just to clarify - Are you using the **setDisplayedValues()** method to display custom values in the numberPicker?
> If yes, then this solution will resolve your issue.
> 
> before calling the **setMinValue()** & **setMaxValue()** method, call this: **setDisplayedValues(null)**. So the flow should be somewhat like this:
> 
> **mNumberPicker.setDisplayedValues(null);**
> **mNumberPicker.setMinValue(1);**
> **mNumberPicker.setMaxValue(mDisplayValues.length);**
> **mNumberPicker.setDisplayedValues(mDisplayValues);**
> 
> Hope this helps. Good luck!

Love u bro
