### ISSUE TITLE
ResourceNotFoundException (NumberPicker.java line 673)

### ISSUE THREAD

**Issue by ribafish** [ShawnLin013/NumberPicker#135]
Hello,

We've been getting a crash in Firebase that NumberPicker is the cause of. I'm using version 2.4.7 of NumberPicker. The resource ID 0x7f0800ce is found in AndroidStudio in R.java as `np_numberpicker_selection_divider`. I can't find a reference to that in your source files, so I'm at a bit of a loss.
This is the crash (we can't reproduce it):

`Caused by android.view.InflateException: Binary XML file line #50: Binary XML file line #50: Error inflating class com.shawnlin.numberpicker.NumberPicker
Caused by android.view.InflateException: Binary XML file line #50: Error inflating class com.shawnlin.numberpicker.NumberPicker
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f0800ce
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
       at android.content.res.Resources.getDrawable(Resources.java:770)
       at android.content.res.XResources.getDrawable(XResources.java:790)
       at android.content.Context.getDrawable(Context.java:525)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
       at com.shawnlin.numberpicker.NumberPicker.(NumberPicker.java:673)
       at com.shawnlin.numberpicker.NumberPicker.(NumberPicker.java:655)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
       at android.view.LayoutInflater.inflate(<Xposed>)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at android.view.View.inflate(View.java:21010)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
       at android.view.LayoutInflater.inflate(<Xposed>)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2440)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:885)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2609)
       at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2581)
       at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:278)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:407)
       at android.app.Activity.performPause(Activity.java:6819)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3665)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`

**Comment by ribafish** [comment]
PS: I've seen it happen only on a Nexus 6 device, running Android 7.1.1.

**Comment by ribafish** [comment]
@ShawnLin013 I have formatted my pc (for unrelated reasons), and installed everything fresh, which means it's not accessing some older configurations, as gradle downloaded only the 2.4.7 version (I also confirmed that in the gradle cache folder).

**Comment by ShawnLin013** [comment]
Hi @ribafish, I have tested this issue on Nexus 6 with Android 7.1.1 in Emulator of Android Studio. It works correctly. The `np_numberpicker_selection_divider` resource has been deleted from v2.4.8. Reopen this issue when it happened again.
