### ISSUE TITLE
np_wheelItemCount cannot be set to 1

### ISSUE THREAD

**Issue by alexzaitsev** [ShawnLin013/NumberPicker#86]
Just set `np_wheelItemCount` to `1` and try to scroll. You'll get crash:

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                       at com.shawnlin.numberpicker.NumberPicker.decrementSelectorIndices(NumberPicker.java:1775)
                                                                       at com.shawnlin.numberpicker.NumberPicker.scrollBy(NumberPicker.java:1084)
                                                                       at com.shawnlin.numberpicker.NumberPicker.computeScroll(NumberPicker.java:1005)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15167)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15140)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Is it possible to archieve an effect like this: https://prnt.sc/i0c0kr ?

**Comment by ShawnLin013** [comment]
Have you tried setting the text color to transparent?

**Comment by ShawnLin013** [comment]
Ref to #57.
